site_name: Portfólio de Pedro Lima
#site_url: https://peuvitor.github.io

theme:
  logo: images/monitor.png
  language: pt
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      title: Nesta página

nav:
  - Sobre mim: index.md
  - Projetos - Engenharia de Dados:
    - projects-de/index.md
    - ETL AWS: projects-de/etl-aws.md
  - Projetos - Ciência de Dados:
    - projects-ds/index.md
    - Detecção de fraude: projects-ds/fraud-detection.md



